log_level = "info"
log_format = "pretty"
# The chain name is the Chain ID value without what is after the '.' (e.g 'shielded-expedition.88f17d1d14' -> 'shielded-expedition')
chain_name = "public-testnet-15"

[database]
host = "localhost"
user = "postgres"
password = "wow"
dbname = "blockchain"
port = 5432
# Optional field to configure a timeout if database connection 
# fails.
connection_timeout = 20
create_index = true

[server]
serve_at = "0.0.0.0"
port = 30303

[indexer]
tendermint_addr = "http://127.0.0.1"

[jaeger]
enable = false
host = "localhost"
port = 6831

[prometheus]
host = "0.0.0.0"
port = 9000
