name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
jobs:
  security_audit:
    runs-on: zondax-runners
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      # - uses: EmbarkStudios/cargo-deny-action@v1
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
