name: Security audit
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
jobs:
  security_audit:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v3
      - uses: EmbarkStudios/cargo-deny-action@v1
      # - name: Scan for vulnerabilities
      #   run: cargo deny check advisories
