name: Tests

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  sync_test:
    name: Testing syncing
    runs-on: [self-hosted, linux, x64]
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: wow
          POSTGRES_DB: blockchain
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler build-essential pkg-config libssl-dev
          make download-checksum
          protoc --version
      - name: Tests saving blocks
        run: | 
          cargo test save_block -- --test-threads=1
      - name: Tests getting blocks
        run: |
          cargo test block_tests
